# Generated by Django 5.2.7 on 2025-12-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlitts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlitt',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='tagged_tlitts', to='tlitts.hashtag'),
        ),
    ]
