# Generated by Django 5.2.7 on 2025-12-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlitts', '0002_tlitt_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='tlitts',
        ),
    ]
