# Generated by Django 5.2.7 on 2025-12-12 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlitts', '0003_remove_hashtag_tlitts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'permissions': [('can edit and delete all comments', 'Użytkownik może edytować i usuwać komentarze każdego')]},
        ),
        migrations.AlterModelOptions(
            name='hashtag',
            options={'ordering': ['contents'], 'permissions': [('can edit and delete hashtags', 'Użytkownik może edytować i usuwać istniejące hashtagi')]},
        ),
        migrations.AlterModelOptions(
            name='tlitt',
            options={'ordering': ['-created_at'], 'permissions': [('can edit and delete all tlitts', 'Użytkownik może edytować i usuwać posty każdego')]},
        ),
    ]
