# Generated by Django 5.2.7 on 2025-12-12 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlitts', '0004_alter_comment_options_alter_hashtag_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tlitt',
            options={'ordering': ['-created_at'], 'permissions': [('tlitts.can_edit_and_delete_tlitts', 'Użytkownik może edytować i usuwać posty każdego')]},
        ),
    ]
