# Generated by Django 5.2.7 on 2025-12-12 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlitts', '0005_alter_tlitt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tlitt',
            options={'ordering': ['-created_at'], 'permissions': [('tlitts.can_edit_and_delete_tlitts', 'User can edit post of anybody')]},
        ),
    ]
