# Generated by Django 5.2.7 on 2025-12-12 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlitts', '0006_alter_tlitt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='hashtag',
            options={'ordering': ['contents']},
        ),
        migrations.AlterModelOptions(
            name='tlitt',
            options={'ordering': ['-created_at']},
        ),
    ]
