# Generated by Django 5.2.7 on 2025-12-12 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlitts', '0007_alter_comment_options_alter_hashtag_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'permissions': [('can edit and delete all comments', 'Użytkownik może edytować i usuwać komentarze każdego')]},
        ),
    ]
