# Generated by Django 5.2.7 on 2025-12-12 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlitts', '0009_alter_comment_options_alter_tlitt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tlitt',
            options={'ordering': ['-created_at'], 'permissions': [('tlitts.can_edit_and_delete_tlitts', 'User can edit post of anybody'), ('tlitts.can_editdele', 'User can edit and dele stuff tweets')]},
        ),
    ]
