# Generated by Django 5.2.7 on 2025-12-12 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlitts', '0010_alter_tlitt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tlitt',
            options={'ordering': ['-created_at'], 'permissions': [('tlitts.can_edit_and_delete_tlitts', 'User can edit post of anybody'), ('tlitts.can_editdele', 'User can edit and dele stuff tweets'), ('tlitts.change_tlitt', 'tlitts change tlitt')]},
        ),
    ]
