# Generated by Django 5.2.7 on 2025-12-12 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlitts', '0011_alter_tlitt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tlitt',
            options={'ordering': ['-created_at'], 'permissions': [('tlitts.change_tlitt', 'tlitts change tlitt')]},
        ),
    ]
