# Generated by Django 5.2.7 on 2025-12-12 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlitts', '0012_alter_tlitt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'permissions': [('tlitts.change_comment', 'tlitts change comment')]},
        ),
        migrations.AlterModelOptions(
            name='hashtag',
            options={'ordering': ['contents'], 'permissions': [('tlitts.change_hashtag', 'tlitts change hashtag')]},
        ),
    ]
