# Generated by Django 5.2.7 on 2025-12-12 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlitts', '0013_alter_comment_options_alter_hashtag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tlitt',
            options={'ordering': ['-created_at'], 'permissions': [('tlitts.change_tlitt', 'tlitts change tlitt'), ('edit_delete_all_tlitts', 'Użytkownik może edytować i usuwać posty każdego')]},
        ),
    ]
