# Generated by Django 5.2.7 on 2025-12-12 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlitts', '0015_alter_tlitt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'permissions': [('tlitts.change_comment', 'tlitts change comment'), ('edit_delete_all_comments', 'Użytkownik może edytować i usuwać komentarz każdego takkk')]},
        ),
        migrations.AlterModelOptions(
            name='hashtag',
            options={'ordering': ['contents'], 'permissions': [('tlitts.change_hashtag', 'tlitts change hashtag'), ('edit_delete_all_hashtag', 'Użytkownik może edytować i usuwać hasztagi takkk')]},
        ),
    ]
